# Generated by Django 4.2.11 on 2024-04-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_rename_descriprion_products_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
